### ISSUE TITLE
How to get selected element id ?

### ISSUE THREAD

**Issue by kbsystems** [sarn/ARNRouletteWheelView#2]
Hello,

Good work Sarn. I implemented your library but I don't know how to get ID of selected item,
Is any method to get this ?

**Comment by sarn** [comment]
Hi there

I don't know for what you need an ID, I assume that you need to find out which cell got selected. If that is the case, you could implement the `UICollectionViewDelegate` method `- (void)collectionView:(UICollectionView *)collectionView didSelectItemAtIndexPath:(NSIndexPath *)indexPath`

The `NSIndexPath` has all the information you need to know which cell got selected. Remember `ARNRouletteWheelView` is just a `UICollectionView`. So you could use all the data source and delegate methods provided by the standard `UICollectionView`.

If you need to have a specific ID for every cell, you could add this as a property to your custom `ARNRouletteWheelCell` implementation.

**Comment by kbsystems** [comment]
Ok thx
